import {
  customType,
  integer,
  numeric,
  real,
  sqliteTable,
  text,
  unique,
} from "drizzle-orm/sqlite-core";

export const operLog = sqliteTable("OperLog", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  operDate: numeric("OperDate"),
  operName: customType({ dataType: () => "CHAR(100)" })("OperName"),
  logInfo: customType({ dataType: () => "CHAR(1024)" })("LogInfo"),
});

export const alxInfo = sqliteTable("AlxInfo", {
  alxid: integer("ALXID").primaryKey({ autoIncrement: true }),
  alxname: text("ALXNAME"),
  yblCt: text("YBL_CT"),
  yblXhc: text("YBL_XHC"),
  yblLz: text("YBL_LZ"),
  isdefault: text("ISDEFAULT"),
});

export const userManager = sqliteTable("UserManager", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  userName: text("UserName"),
  pwd: text("Pwd"),
  name: text("Name"),
  power: text("Power"),
  regTime: text("RegTime"),
});

export const sysConfig = sqliteTable(
  "SysConfig",
  {
    recId: integer("RecID").primaryKey({ autoIncrement: true }),
    typeName: text("TypeName"),
    configKey: text("ConfigKey"),
    configValue: text("ConfigValue"),
    defaultValue: text("DefaultValue"),
    remark: text("Remark"),
  },
  (table) => [unique("SysConfig_ConfigKey_unique").on(table.configKey)],
);

export const yqConfig = sqliteTable("YQConfig", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  factoryName: text("FactoryName"),
  yqName: text("YQName"),
  yqid: text("YQID"),
  channelNums: integer("ChannelNums"),
  productionDate: text("ProductionDate"),
  installationDate: text("InstallationDate"),
  commMode: integer("CommMode"),
  commParam: text("CommParam"),
  commParamBack: text("CommParamBack"),
  dllPath: text("DllPath"),
  usedFlag: integer("UsedFlag"),
});

export const channels = sqliteTable("Channels", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  nBoardIndex: integer(),
  nChannelIndex: integer(),
  nPhysicsIndex: integer(),
  nWheelIndex: integer(),
  szWheelName: text(),
  szName: text(),
  nSleep: integer(),
  nSmooth: integer(),
  ftRange: real(),
  nPluse: integer(),
  nDelay: integer(),
  nAtten: integer(),
  nDbSub: integer(),
  bActive: integer(),
});

export const gates = sqliteTable("Gates", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  nBoardIndex: integer(),
  nChannelIndex: integer(),
  nChannelRectId: integer(),
  szGateName: text(),
  nGateId: integer(),
  nSubGateId: integer(),
  szColor: text(),
  bActive: integer(),
  nLeft: integer(),
  nWidth: integer(),
  nTop: integer(),
  nBleft: integer(),
  nBwidth: integer(),
  nBtop: integer(),
  nB1Count: integer().default(0),
  nB1Width: integer().default(0),
  nB1Height: integer().default(0),
  nB2Count: integer().default(0),
  nB2Width: integer().default(0),
  nB2Height: integer().default(0),
  nE1Count: integer().default(0),
  nE1Width: integer().default(0),
  nE1Height: integer().default(0),
  nE2Count: integer().default(0),
  nE2Width: integer().default(0),
  nE2Height: integer().default(0),
  bSelected: integer(),
});

export const quartorChannel = sqliteTable("QuartorChannel", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  nBoardIndex: integer(),
  nChannelIndex: integer(),
  nPhysicsIndex: integer(),
  nWheelIndex: integer(),
  szWheelName: text(),
  szName: text(),
  nSleep: integer(),
  nSmooth: integer(),
  ftRange: real(),
  nPluse: integer(),
  nDelay: integer(),
  nAtten: integer(),
  nDbSub: integer(),
  bActive: integer(),
});

export const quartorGates = sqliteTable("QuartorGates", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  nBoardIndex: integer(),
  nChannelIndex: integer(),
  nChannelRectId: integer(),
  szGateName: text(),
  nGateId: integer(),
  nSubGateId: integer(),
  szColor: text(),
  bActive: integer(),
  nLeft: integer(),
  nWidth: integer(),
  nTop: integer(),
  nBleft: integer(),
  nBwidth: integer(),
  nBtop: integer(),
  nB1Count: integer().default(0),
  nB1Width: integer().default(0),
  nB1Height: integer().default(0),
  nB2Count: integer().default(0),
  nB2Width: integer().default(0),
  nB2Height: integer().default(0),
  nE1Count: integer().default(0),
  nE1Width: integer().default(0),
  nE1Height: integer().default(0),
  nE2Count: integer().default(0),
  nE2Width: integer().default(0),
  nE2Height: integer().default(0),
  bSelected: integer(),
});

export const quartorRecordInfo = sqliteTable("QuartorRecordInfo", {
  recId: integer("RecID").primaryKey({ autoIncrement: true }),
  szUserName: text(),
  tmNow: numeric(),
  szIds: text(),
  nBoardIndex: integer(),
  nChannelIndex: integer(),
  bResult: customType({ dataType: () => "BOOL" })(),
  bHorResult: customType({ dataType: () => "BOOL" })(),
  nHorAtten: integer(),
  fHorB0: real("fHor_B0"),
  fHorB1: real("fHor_B1"),
  fHorB2: real("fHor_B2"),
  fHorB3: real("fHor_B3"),
  fHorB4: real("fHor_B4"),
  fHorB5: real("fHor_B5"),
  fHorB0Llz: real("fHor_B0_LLZ"),
  fHorB1Llz: real("fHor_B1_LLZ"),
  fHorB2Llz: real("fHor_B2_LLZ"),
  fHorB3Llz: real("fHor_B3_LLZ"),
  fHorB4Llz: real("fHor_B4_LLZ"),
  fHorB5Llz: real("fHor_B5_LLZ"),
  fHorResult: real(),
  bDesResult: customType({ dataType: () => "BOOL" })(),
  nDesAttenH: integer("nDesAtten_H"),
  nDesAttenL: integer("nDesAtten_L"),
  nDesAtten: integer(),
  bAttResult: customType({ dataType: () => "BOOL" })(),
  fAttS0: real("fAtt_S0"),
  fAttS1: real("fAtt_S1"),
  fAttS: real("fAtt_S"),
  bVerResult: customType({ dataType: () => "BOOL" })(),
  fVerB0: real("fVer_B0"),
  fVerB1: real("fVer_B1"),
  fVerB2: real("fVer_B2"),
  fVerB3: real("fVer_B3"),
  fVerB4: real("fVer_B4"),
  fVerB5: real("fVer_B5"),
  fVerB6: real("fVer_B6"),
  fVerB7: real("fVer_B7"),
  fVerB8: real("fVer_B8"),
  fVerB9: real("fVer_B9"),
  fVerB10: real("fVer_B10"),
  fVerB11: real("fVer_B11"),
  fVerB12: real("fVer_B12"),
  fVerB13: real("fVer_B13"),
  fVerTgMaxB0: real("fVerTgMax_B0"),
  fVerTgMaxB1: real("fVerTgMax_B1"),
  fVerTgMaxB2: real("fVerTgMax_B2"),
  fVerTgMaxB3: real("fVerTgMax_B3"),
  fVerTgMaxB4: real("fVerTgMax_B4"),
  fVerTgMaxB5: real("fVerTgMax_B5"),
  fVerTgMaxB6: real("fVerTgMax_B6"),
  fVerTgMaxB7: real("fVerTgMax_B7"),
  fVerTgMaxB8: real("fVerTgMax_B8"),
  fVerTgMaxB9: real("fVerTgMax_B9"),
  fVerTgMaxB10: real("fVerTgMax_B10"),
  fVerTgMaxB11: real("fVerTgMax_B11"),
  fVerTgMaxB12: real("fVerTgMax_B12"),
  fVerTgMaxB13: real("fVerTgMax_B13"),
  nDynS1: integer("nDyn_S1"),
  nDynS2: integer("nDyn_S2"),
  nDynMax: integer("nDyn_MAX"),
});
