export const flatRoutes = [
  // { title: "404", path: "*" },
  // { title: "home", path: "/" },
  { title: "设置", path: "/settings" },
  { title: "日志", path: "/log" },
  { title: "现车作业", path: "/detection" },
  { title: "日常校验", path: "/verify" },
  { title: "季度校验", path: "/quartors" },
  { title: "华兴致远HMIS", path: "/hxzy" },
  { title: "华兴致远日常校验", path: "/hxzy/verifies" },
  { title: "华兴致远HMIS设置", path: "/hxzy/setting" },
  { title: "京天威HMIS", path: "/jtv" },
  { title: "京天威HMIS设置", path: "/jtv/setting" },
  { title: "京天威(徐州北)HMIS", path: "/jtv_xuzhoubei" },
  { title: "京天威(徐州北)HMIS设置", path: "/jtv_xuzhoubei/setting" },
  { title: "康华HMIS", path: "/kh" },
  { title: "康华HMIS设置", path: "/kh/setting" },
];
