networks:
  app_net:
    driver: bridge
    external: false

# volumes:
#   pgdata:
#     driver: local

services:
  linux-builder:
    build:
      context: .
      args:
        ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
        ELECTRON_BUILDER_BINARIES_MIRROR: https://npmmirror.com/mirrors/electron-builder-binaries/
        NODE_JS_ORG_MIRROR: https://npmmirror.com/mirrors/node/
        NPM_CONFIG_DISTURL: https://npmmirror.com/mirrors/node/
    image: builder:linux
    container_name: build_linux
    volumes:
      - ./packages/electron-app/release:/output_dist
