networks:
  app_net:
    driver: bridge
    external: false

# volumes:
#   pgdata:
#     driver: local

services:
  linux-builder:
    build:
      context: .
    image: builder:linux
    container_name: build_linux
    volumes:
      - ./packages/electron-app/release:/output_dist
