CREATE TABLE `AlxInfo` (
	`ALXID` integer PRIMARY KEY AUTOINCREMENT,
	`ALXNAME` text,
	`YBL_CT` text,
	`YBL_XHC` text,
	`YBL_LZ` text,
	`HALF_ALXLEN` real,
	`FTRADIUS` real,
	`FTRADIUS0` real,
	`FTRADIUS1` real,
	`FTRADIUS2` real,
	`FTRADIUS3` real,
	`FTRADIUS4` real,
	`FTRADIUS5` real,
	`FTRADIUS6` real,
	`FTRADIUS7` real,
	`FTLENGTH0` real,
	`FTLENGTH1` real,
	`FTLENGTH2` real,
	`AVGSPEED` real,
	`ISDEFAULT` BOOL
);
--> statement-breakpoint
CREATE TABLE `Channels` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`nBoardIndex` integer,
	`nChannelIndex` integer,
	`nPhysicsIndex` integer,
	`nWheelIndex` integer,
	`szWheelName` text,
	`szName` text,
	`nSleep` integer,
	`nSmooth` integer,
	`ftRange` real,
	`nPluse` integer,
	`nDelay` integer,
	`nAtten` integer,
	`nDbSub` integer,
	`nWangle` integer,
	`nZsize` integer,
	`ftDistance` real,
	`bActive` integer
);
--> statement-breakpoint
CREATE TABLE `detections_data` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`PRecID` integer,
	`szIds` text,
	`nBoard` integer,
	`nChannel` integer,
	`nPhyChannel` integer,
	`nTaIndex` integer,
	`nAtten` integer,
	`nDbSub` integer,
	`nFwIndex` integer,
	`nFwIn` integer,
	`nFwOut` integer,
	`nFwCount` integer,
	`fltValueX` real,
	`fltValueY` real,
	`fltValueUs` real,
	`fltValueUsh` real,
	`nWangle` integer,
	`szRemark` text,
	`bDeleted` BOOL
);
--> statement-breakpoint
CREATE TABLE `detectors` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`szIds` text CONSTRAINT `detectors_szIDs_unique` UNIQUE,
	`szWhModel` text,
	`szUsername` text,
	`szDh` text,
	`szZh` text,
	`szSrdw` text,
	`szSryy` text,
	`szTmMake` text,
	`szIdsMake` text,
	`szTmFirst` text,
	`szIdsFirst` text,
	`szTmLast` text,
	`szIdsLast` text,
	`ftRadiu` real,
	`bFlaws` BOOL,
	`bWheelLs` BOOL,
	`bWheelRs` BOOL,
	`bSickLd` BOOL,
	`bSickRd` BOOL,
	`tmNow` numeric,
	`szResult` text,
	`szMemo` text,
	`startTime` numeric,
	`endTime` numeric,
	`bIsEnable` BOOL
);
--> statement-breakpoint
CREATE TABLE `Gates` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`nBoardIndex` integer,
	`nChannelIndex` integer,
	`nChannelRectId` integer,
	`szGateName` text,
	`nGateId` integer,
	`nSubGateId` integer,
	`szColor` text,
	`bActive` integer,
	`nLeft` integer,
	`nWidth` integer,
	`nTop` integer,
	`nBleft` integer,
	`nBwidth` integer,
	`nBtop` integer,
	`nB1Count` integer DEFAULT 0,
	`nB1Width` integer DEFAULT 0,
	`nB1Height` integer DEFAULT 0,
	`nB2Count` integer DEFAULT 0,
	`nB2Width` integer DEFAULT 0,
	`nB2Height` integer DEFAULT 0,
	`nE1Count` integer DEFAULT 0,
	`nE1Width` integer DEFAULT 0,
	`nE1Height` integer DEFAULT 0,
	`nE2Count` integer DEFAULT 0,
	`nE2Width` integer DEFAULT 0,
	`nE2Height` integer DEFAULT 0,
	`bSelected` integer
);
--> statement-breakpoint
CREATE TABLE `OperLog` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`OperDate` numeric,
	`OperName` CHAR(100),
	`LogInfo` CHAR(1024)
);
--> statement-breakpoint
CREATE TABLE `QuartorChannel` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`nBoardIndex` integer,
	`nChannelIndex` integer,
	`nPhysicsIndex` integer,
	`nWheelIndex` integer,
	`szWheelName` text,
	`szName` text,
	`nSleep` integer,
	`nSmooth` integer,
	`ftRange` real,
	`nPluse` integer,
	`nDelay` integer,
	`nAtten` integer,
	`nDbSub` integer,
	`nWangle` integer,
	`nZsize` integer,
	`ftDistance` real,
	`bActive` integer
);
--> statement-breakpoint
CREATE TABLE `QuartorGates` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`nBoardIndex` integer,
	`nChannelIndex` integer,
	`nChannelRectId` integer,
	`szGateName` text,
	`nGateId` integer,
	`nSubGateId` integer,
	`szColor` text,
	`bActive` integer,
	`nLeft` integer,
	`nWidth` integer,
	`nTop` integer,
	`nBleft` integer,
	`nBwidth` integer,
	`nBtop` integer,
	`nB1Count` integer DEFAULT 0,
	`nB1Width` integer DEFAULT 0,
	`nB1Height` integer DEFAULT 0,
	`nB2Count` integer DEFAULT 0,
	`nB2Width` integer DEFAULT 0,
	`nB2Height` integer DEFAULT 0,
	`nE1Count` integer DEFAULT 0,
	`nE1Width` integer DEFAULT 0,
	`nE1Height` integer DEFAULT 0,
	`nE2Count` integer DEFAULT 0,
	`nE2Width` integer DEFAULT 0,
	`nE2Height` integer DEFAULT 0,
	`bSelected` integer
);
--> statement-breakpoint
CREATE TABLE `QuartorRecordInfo` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`szUserName` text,
	`tmNow` numeric,
	`szIds` text,
	`nBoardIndex` integer,
	`nChannelIndex` integer,
	`bResult` BOOL,
	`bHorResult` BOOL,
	`nHorAtten` integer,
	`fHor_B0` real,
	`fHor_B1` real,
	`fHor_B2` real,
	`fHor_B3` real,
	`fHor_B4` real,
	`fHor_B5` real,
	`fHor_B0_LLZ` real,
	`fHor_B1_LLZ` real,
	`fHor_B2_LLZ` real,
	`fHor_B3_LLZ` real,
	`fHor_B4_LLZ` real,
	`fHor_B5_LLZ` real,
	`fHorResult` real,
	`bDesResult` BOOL,
	`nDesAtten_H` integer,
	`nDesAtten_L` integer,
	`nDesAtten` integer,
	`bAttResult` BOOL,
	`fAtt_S0` real,
	`fAtt_S1` real,
	`fAtt_S` real,
	`bVerResult` BOOL,
	`fVer_B0` real,
	`fVer_B1` real,
	`fVer_B2` real,
	`fVer_B3` real,
	`fVer_B4` real,
	`fVer_B5` real,
	`fVer_B6` real,
	`fVer_B7` real,
	`fVer_B8` real,
	`fVer_B9` real,
	`fVer_B10` real,
	`fVer_B11` real,
	`fVer_B12` real,
	`fVer_B13` real,
	`fVerTgMax_B0` real,
	`fVerTgMax_B1` real,
	`fVerTgMax_B2` real,
	`fVerTgMax_B3` real,
	`fVerTgMax_B4` real,
	`fVerTgMax_B5` real,
	`fVerTgMax_B6` real,
	`fVerTgMax_B7` real,
	`fVerTgMax_B8` real,
	`fVerTgMax_B9` real,
	`fVerTgMax_B10` real,
	`fVerTgMax_B11` real,
	`fVerTgMax_B12` real,
	`fVerTgMax_B13` real,
	`nDyn_S1` integer,
	`nDyn_S2` integer,
	`nDyn_MAX` integer
);
--> statement-breakpoint
CREATE TABLE `quartors` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`szIds` text CONSTRAINT `quartors_szIDs_unique` UNIQUE,
	`szWhModel` text,
	`szUsername` text,
	`szDh` text,
	`szZh` text,
	`szSrdw` text,
	`szSryy` text,
	`szTmMake` text,
	`szIdsMake` text,
	`szTmFirst` text,
	`szIdsFirst` text,
	`szTmLast` text,
	`szIdsLast` text,
	`ftRadiu` real,
	`bFlaws` BOOL,
	`bWheelLs` BOOL,
	`bWheelRs` BOOL,
	`bSickLd` BOOL,
	`bSickRd` BOOL,
	`tmNow` numeric,
	`szResult` text,
	`szMemo` text,
	`startTime` numeric,
	`endTime` numeric,
	`bIsEnable` BOOL
);
--> statement-breakpoint
CREATE TABLE `quartors_data` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`PRecID` integer,
	`szIds` text,
	`nBoard` integer,
	`nChannel` integer,
	`nPhyChannel` integer,
	`nTaIndex` integer,
	`nAtten` integer,
	`nDbSub` integer,
	`nFwIndex` integer,
	`nFwIn` integer,
	`nFwOut` integer,
	`nFwCount` integer,
	`fltValueX` real,
	`fltValueY` real,
	`fltValueUs` real,
	`fltValueUsh` real,
	`nWangle` integer,
	`szRemark` text,
	`bDeleted` BOOL
);
--> statement-breakpoint
CREATE TABLE `SysConfig` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`TypeName` text,
	`ConfigKey` text CONSTRAINT `SysConfig_ConfigKey_unique` UNIQUE,
	`ConfigValue` text,
	`DefaultValue` text,
	`Remark` text,
	`IsReadOnly` BOOL
);
--> statement-breakpoint
CREATE TABLE `UserManager` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`UserName` text,
	`Pwd` text,
	`Name` text,
	`Power` text,
	`RegTime` text
);
--> statement-breakpoint
CREATE TABLE `verifies` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`szIds` text CONSTRAINT `verifies_szIDs_unique` UNIQUE,
	`szWhModel` text,
	`szUsername` text,
	`szDh` text,
	`szZh` text,
	`szSrdw` text,
	`szSryy` text,
	`szTmMake` text,
	`szIdsMake` text,
	`szTmFirst` text,
	`szIdsFirst` text,
	`szTmLast` text,
	`szIdsLast` text,
	`ftRadiu` real,
	`bFlaws` BOOL,
	`bWheelLs` BOOL,
	`bWheelRs` BOOL,
	`bSickLd` BOOL,
	`bSickRd` BOOL,
	`tmNow` numeric,
	`szResult` text,
	`szMemo` text,
	`startTime` numeric,
	`endTime` numeric,
	`bIsEnable` BOOL
);
--> statement-breakpoint
CREATE TABLE `verifies_data` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`PRecID` integer,
	`szIds` text,
	`nBoard` integer,
	`nChannel` integer,
	`nPhyChannel` integer,
	`nTaIndex` integer,
	`nAtten` integer,
	`nDbSub` integer,
	`nFwIndex` integer,
	`nFwIn` integer,
	`nFwOut` integer,
	`nFwCount` integer,
	`fltValueX` real,
	`fltValueY` real,
	`fltValueUs` real,
	`fltValueUsh` real,
	`nWangle` integer,
	`szRemark` text,
	`bDeleted` BOOL
);
--> statement-breakpoint
CREATE TABLE `YQConfig` (
	`RecID` integer PRIMARY KEY AUTOINCREMENT,
	`FactoryName` text,
	`YQName` text,
	`YQID` text,
	`ChannelNums` integer,
	`ProductionDate` text,
	`InstallationDate` text,
	`CommMode` integer,
	`CommParam` text,
	`CommParamBack` text,
	`DllPath` text,
	`UsedFlag` integer
);
